In [1]:
# Importando Biblioteca
import pandas as pd
import numpy as np
import pyarrow.parquet as pq

# Configuração Global Pandas - formata float com 2 casas decimais
pd.set_option('display.float_format', '{:.2f}'.format)

# Configuração Global Pandas - mostra todas as colunas do df
pd.set_option('display.max_columns', None)

In [2]:
# Carregando base de dados
dfm = pd.read_parquet("../data/amazon_tratada.parquet")
dfm

,product_id,product_name,Category n0,Category n1,Category n2,Category n3,Category n4,Category n5,Category n6,actual_price,discount_percentage,discounted_price,full_discount,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,1099.00,0.64,399.00,700.00,4.20,24269.00,High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,349.00,0.43,199.00,150.00,4.00,43994.00,"Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,1899.00,0.90,199.00,1700.00,3.90,7928.00,【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a..."
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,699.00,0.53,329.00,370.00,4.20,94363.00,The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou..."
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,399.00,0.61,154.00,245.00,4.20,16905.00,[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1460,B08L7J3T31,Noir Aqua - 5pcs PP Spun Filter + 1 Spanner | ...,Home&Kitchen,Kitchen&HomeAppliances,WaterPurifiers&Accessories,WaterPurifierAccessories,-,-,-,919.00,0.59,379.00,540.00,4.00,1090.00,SUPREME QUALITY 90 GRAM 3 LAYER THIK PP SPUN F...,"AHITFY6AHALOFOHOZEOC6XBP4FEA,AFRABBODZJZQB6Z4U...","Prabha ds,Raghuram bk,Real Deal,Amazon Custome...","R3G3XFHPBFF0E8,R3C0BZCD32EIGW,R2EBVBCN9QPD9R,R...","Received the product without spanner,Excellent...","I received product without spanner,Excellent p..."
1461,B01M6453MB,Prestige Delight PRWO Electric Rice Cooker (1 ...,Home&Kitchen,Kitchen&HomeAppliances,SmallKitchenAppliances,Rice&PastaCookers,-,-,-,3045.00,0.25,2280.00,765.00,4.10,4118.00,"230 Volts, 400 watts, 1 Year","AFG5FM3NEMOL6BNFRV2NK5FNJCHQ,AGEINTRN6Z563RMLH...","Manu Bhai,Naveenpittu,Evatira Sangma,JAGANNADH...","R3DDL2UPKQ2CK9,R2SYYU1OATVIU5,R1VM993161IYRW,R...","ok,everything was good couldn't return bcoz I ...","ok,got everything as mentioned but the measuri..."
1462,B009P2LIL4,Bajaj Majesty RX10 2000 Watts Heat Convector R...,Home&Kitchen,"Heating,Cooling&AirQuality",RoomHeaters,HeatConvectors,-,-,-,3080.00,0.28,2219.00,861.00,3.60,468.00,International design and styling|Two heat sett...,"AGVPWCMAHYQWJOQKMUJN4DW3KM5Q,AF4Q3E66MY4SR7YQZ...","Nehal Desai,Danish Parwez,Amazon Customer,Amaz...","R1TLRJVW4STY5I,R2O455KRN493R1,R3Q5MVGBRIAS2G,R...","very good,Work but front melt after 2 month,Go...","plastic but cool body ,u have to find sturdy s..."
1463,B00J5DYCCA,Havells Ventil Air DSP 230mm Exhaust Fan (Pist...,Home&Kitchen,"Heating,Cooling&AirQuality",Fans,ExhaustFans,-,-,-,1890.00,0.26,1399.00,491.00,4.00,8031.00,Fan sweep area: 230 MM ; Noise level: (40 - 45...,"AF2JQCLSCY3QJATWUNNHUSVUPNQQ,AFDMLUXC5LS5RXDJS...","Shubham Dubey,E.GURUBARAN,Mayank S.,eusuf khan...","R39Q2Y79MM9SWK,R3079BG1NIH6MB,R29A31ZELTZNJM,R...","Fan Speed is slow,Good quality,Good product,go...",I have installed this in my kitchen working fi...
1464,B01486F4G6,Borosil Jumbo 1000-Watt Grill Sandwich Maker (...,Home&Kitchen,Kitchen&HomeAppliances,SmallKitchenAppliances,SandwichMakers,-,-,-,3690.00,0.22,2863.00,827.00,4.30,6987.00,"Brand-Borosil, Specification â€“ 23V ~ 5Hz;1 W...","AFGW5PT3R6ZAVQR4Y5MWVAKBZAYA,AG7QNJ2SCS5VS5VYY...","Rajib,Ajay B,Vikas Kahol,PARDEEP,Anindya Prama...","R20RBRZ0WEUJT9,ROKIFK9R2ISSE,R30EEG2FNJSN5I,R2...","Works perfect,Ok good product,Nice Product. Re...",It does it job perfectly..only issue is temp c...

In [3]:
dfm.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   Category n0          1465 non-null   str
 3   Category n1          1465 non-null   str
 4   Category n2          1465 non-null   str
 5   Category n3          1465 non-null   str
 6   Category n4          1465 non-null   str
 7   Category n5          1465 non-null   str
 8   Category n6          1465 non-null   str
 9   actual_price         1465 non-null   float64
 10  discount_percentage  1465 non-null   float64
 11  discounted_price     1465 non-null   float64
 12  full_discount        1465 non-null   float64
 13  rating               1465 non-null   float64
 14  rating_count         1465 non-null   float64
 15  about_product        1465 non-null   str
 16  user_id              1465 non-null   str
 17  user_name            1465 non-null   str
 18  review_id            1465 non-null   str
 19  review_title         1465 non-null   str
 20  review_content       1465 non-null   str
dtypes: float64(6), str(15)
memory usage: 4.4 MB

In [4]:
# Quantidade de produtos únicos
prod_uniq = dfm['product_name'].nunique()
prod_uniq

1337

In [5]:
# Contando quantidade de produtos por categorias principais

qtd_produtos = (dfm
                .groupby('Category n0')['product_id']
                .nunique()
                .reset_index(name='qtd_produtos')
                .sort_values(by='qtd_produtos', ascending=False).iloc[0]
                )

print(qtd_produtos['qtd_produtos'])

490

In [6]:
# Considerações 1

print(f'Há ao todo {prod_uniq} produtos únicos na base de dados, distribuídos em {dfm["Category n0"].nunique()} categorias principais, onde a categoria com mais produtos é a \n{qtd_produtos["Category n0"]} com {qtd_produtos["qtd_produtos"]} produtos.')

Há ao todo 1337 produtos únicos na base de dados, distribuídos em 9 categorias principais, onde a categoria com mais produtos é a
Electronics com 490 produtos.

In [7]:
dfm.describe()

,actual_price,discount_percentage,discounted_price,full_discount,rating,rating_count
count,1465.00,1465.00,1465.00,1465.00,1465.00,1465.00
mean,5444.99,0.48,3125.31,2319.68,4.10,18270.57
std,10874.83,0.22,6944.30,4604.47,0.29,42729.99
min,39.00,0.00,39.00,0.00,2.00,1.00
25%,800.00,0.32,325.00,371.00,4.00,1173.00
50%,1650.00,0.50,799.00,800.00,4.10,5178.00
75%,4295.00,0.63,1999.00,1953.00,4.30,17325.00
max,139900.00,0.94,77990.00,61910.00,5.00,426973.00

In [8]:
dfm.describe(include=['number'])

,actual_price,discount_percentage,discounted_price,full_discount,rating,rating_count
count,1465.00,1465.00,1465.00,1465.00,1465.00,1465.00
mean,5444.99,0.48,3125.31,2319.68,4.10,18270.57
std,10874.83,0.22,6944.30,4604.47,0.29,42729.99
min,39.00,0.00,39.00,0.00,2.00,1.00
25%,800.00,0.32,325.00,371.00,4.00,1173.00
50%,1650.00,0.50,799.00,800.00,4.10,5178.00
75%,4295.00,0.63,1999.00,1953.00,4.30,17325.00
max,139900.00,0.94,77990.00,61910.00,5.00,426973.00

In [9]:
dfm.describe()['actual_price']

count     1465.00
mean      5444.99
std      10874.83
min         39.00
25%        800.00
50%       1650.00
75%       4295.00
max     139900.00
Name: actual_price, dtype: float64

In [10]:
# Verificando preço máximo e mínimo
dfm.describe()['actual_price'].iloc[[3,7]]

min       39.00
max   139900.00
Name: actual_price, dtype: float64

In [11]:
# Produtos mais caro e mais barato antes do desconto 

prod_mais_caro = dfm.loc[dfm['actual_price'].idxmax(), 'product_name']
prod_mais_barato = dfm.loc[dfm['actual_price'].idxmin(), 'product_name']
preço_prod_mais_caro = dfm['actual_price'].max()
preço_prod_mais_barato = dfm['actual_price'].min()

print(prod_mais_caro)
print(preço_prod_mais_caro)
print(prod_mais_barato)
print(preço_prod_mais_barato)

Sony Bravia 164 cm (65 inches) 4K Ultra HD Smart LED Google TV KD-65X74K (Black)
139900.0
E-COSMOS 5V 1.2W Portable Flexible USB LED Light (Colours May Vary, Small, EC-POF1)
39.0

In [12]:
dfm.describe()['discounted_price'].iloc[1]

np.float64(3125.3108737201364)

In [13]:
# Comparando a média e a mediana dos produtos com desconto

dfm = dfm.sort_values(by='discounted_price', ascending=False)
media_desc = dfm['discounted_price'].mean()
mediana_desc = dfm['discounted_price'].median()

print(media_desc)
print(mediana_desc)

3125.3108737201364
799.0

In [14]:
# Considerações 2

print(f'O produto mais caro antes do desconto é o {prod_mais_caro} com o valor \nde {preço_prod_mais_caro:.2f}, enquanto o produto mais barato é o {prod_mais_barato} com o valor de {preço_prod_mais_barato:.2f}. \nA média dos preços com desconto é de {media_desc:.2f} e a mediana é de {mediana_desc:.2f}, indicando que os preços estão relativamente distantes, \nmas a média é um pouco maior devido a presença de alguns produtos com descontos mais altos, o que é comum em e-commerces a \nmédia ser bem distante da mediana pela variedade de produtos.')

O produto mais caro antes do desconto é o Sony Bravia 164 cm (65 inches) 4K Ultra HD Smart LED Google TV KD-65X74K (Black) com o valor
de 139900.00, enquanto o produto mais barato é o E-COSMOS 5V 1.2W Portable Flexible USB LED Light (Colours May Vary, Small, EC-POF1) com o valor de 39.00.
A média dos preços com desconto é de 3125.31 e a mediana é de 799.00, indicando que os preços estão relativamente distantes,
mas a média é um pouco maior devido a presença de alguns produtos com descontos mais altos, o que é comum em e-commerces a
média ser bem distante da mediana pela variedade de produtos.

In [15]:
dfm.columns

Index(['product_id', 'product_name', 'Category n0', 'Category n1',
       'Category n2', 'Category n3', 'Category n4', 'Category n5',
       'Category n6', 'actual_price', 'discount_percentage',
       'discounted_price', 'full_discount', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content'],
      dtype='str')

In [16]:
# Produto com maior desconto percentual

prod_maior_desc_p = dfm.loc[dfm['discount_percentage'].idxmax(), 'product_name']
valor_maior_desc_p = dfm[['actual_price', 'discount_percentage','discounted_price', 'full_discount']][dfm['product_name'] == prod_maior_desc_p]

valor_maior_desc_p

     actual_price  discount_percentage  discounted_price  full_discount
695       4999.00                 0.94            294.00        4705.00

In [17]:
# Produto com maior desconto valor (full_discount)

prod_maior_desc_v = dfm.loc[dfm['full_discount'].idxmax(), 'product_name']
valor_maior_desc_v = dfm[['actual_price', 'discount_percentage','discounted_price', 'full_discount']][dfm['product_name'] == prod_maior_desc_v]

valor_maior_desc_v

     actual_price  discount_percentage  discounted_price  full_discount
249     139900.00                 0.44          77990.00       61910.00

In [18]:
# Comparativo valor_maior_desc_v com valor_maior_desc_p

comparativo = pd.concat([valor_maior_desc_v, valor_maior_desc_p])
comparativo

     actual_price  discount_percentage  discounted_price  full_discount
249     139900.00                 0.44          77990.00       61910.00
695       4999.00                 0.94            294.00        4705.00

In [19]:
# Média de descontos por categoria

med_desc_cat = (dfm.groupby('Category n0')['discount_percentage'].mean().reset_index(name='media_desconto').sort_values(by='media_desconto', ascending=False))

med_desc_cat

             Category n0  media_desconto
5        HomeImprovement            0.57
1  Computers&Accessories            0.54
3    Health&PersonalCare            0.53
2            Electronics            0.51
6     MusicalInstruments            0.46
0          Car&Motorbike            0.42
4           Home&Kitchen            0.40
7         OfficeProducts            0.12
8             Toys&Games            0.00

In [20]:
# Considerações 3

print(f'O produto com maior desconto percentual é o \n{prod_maior_desc_p} \ncom um desconto de \n{valor_maior_desc_p["discount_percentage"].values[0]*100:.2f}% e uma economia real de {valor_maior_desc_p["full_discount"].values[0]:.2f}, enquanto o produto com maior desconto em valor é o \n{prod_maior_desc_v} com um desconto de {valor_maior_desc_v["discount_percentage"].values[0]*100:.2f}% e uma economia real de {valor_maior_desc_v["full_discount"].values[0]:.2f}.')
print(f'A categoria com o maior desconto médio é a {med_desc_cat.iloc[0]['Category n0']} com um desconto médio de {med_desc_cat.iloc[0]['media_desconto']*100:.2f}%.')

O produto com maior desconto percentual é o
rts [2 Pack] Mini USB C Type C Adapter Plug, Type C Female to USB A Male Charger Charging Cable Adapter Converter compatible for iPhone, Samsung S20 ultra/S21/S10/S8/S9/MacBook Pro iPad Silver
com um desconto de
94.00% e uma economia real de 4705.00, enquanto o produto com maior desconto em valor é o
Sony Bravia 164 cm (65 inches) 4K Ultra HD Smart LED Google TV KD-65X74K (Black) com um desconto de 44.00% e uma economia real de 61910.00.
A categoria com o maior desconto médio é a HomeImprovement com um desconto médio de 57.50%.

In [21]:
dfm

,product_id,product_name,Category n0,Category n1,Category n2,Category n3,Category n4,Category n5,Category n6,actual_price,discount_percentage,discounted_price,full_discount,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content
249,B09WN3SRC7,Sony Bravia 164 cm (65 inches) 4K Ultra HD Sma...,Electronics,"HomeTheater,TV&Video",Televisions,SmartTelevisions,-,-,-,139900.00,0.44,77990.00,61910.00,4.70,5935.00,Resolution: 4K Ultra HD (3840 x 2160) | Refres...,"AF6Z2OYIXRPZJHVYN2MFKKYHPHFQ,AH5SAORYVUN5MGIBL...","David P.,Dr. ATUL THAKUR,Shriniwas Patil,Tahir...","R16HCZ0W1TRSMM,R12J7UKQ0FX3O9,R8729SR7LQFUU,R1...",Product installation was excellent but delive...,The delivery people were not careful with the ...
325,B095JPKPH3,OnePlus 163.8 cm (65 inches) U Series 4K LED S...,Electronics,"HomeTheater,TV&Video",Televisions,SmartTelevisions,-,-,-,69999.00,0.11,61999.00,8000.00,4.10,6753.00,Resolution: 4K Ultra HD (3840x2160) | Refresh ...,"AG3QTVXT2ODRVKOQJJRDV5KA2F2A,AGEYM57JOHPNX77ZY...","Rashmi,Raghvendra,Hari Prasad P,Vishnu singh,T...","R2PF9QV9JEQO9K,R2NEN86P63G4ES,R302B7X6H0GIC0,R...","Almost Perfect!,Review After using 1month,Nice...",Update after 9 months of use:1. The TV is stil...
255,B0BC8BQ432,VU 164 cm (65 inches) The GloLED Series 4K Sma...,Electronics,"HomeTheater,TV&Video",Televisions,SmartTelevisions,-,-,-,85000.00,0.35,54990.00,30010.00,4.30,3587.00,Resolution: 4K Ultra HD (3840x2160) | Refresh ...,"AHY6AK5LXBTGXDDXSU57ISMDW55Q,AGULFHMPCHCL32WCI...","UtdBuzz,Mukund Nagvenkar,S.R K.,Pruthvi Raj Goud","R2G4T57OLXDVPL,R3IQ8PWVTWENBY,RH6UHEBP622FT,R3...",Good TV for the price. (But my experience was ...,",Screen quality is good.It's been a month I bo..."
283,B0B3XXSB1K,LG 139 cm (55 inches) 4K Ultra HD Smart LED TV...,Electronics,"HomeTheater,TV&Video",Televisions,SmartTelevisions,-,-,-,79990.00,0.40,47990.00,32000.00,4.30,1376.00,Resolution: 4K Ultra HD (3840x2160) | Refresh ...,"AFCWL3MX7BP2ZUDD37MEAENZDQ2A,AGGFXDLCFZMTLJJDR...","Raj Mohammed,Samson,Haroon sayeed,P Imran Khan...","RC3ZLDRM8GA9T,RMDN4PSDM8SKK,R1YFAMDJ7P0SY3,R2W...","Love Amazon but lg is misleading,Amazing produ...",There's no magic remote and lg should include ...
192,B0B15GSPQW,Samsung 138 cm (55 inches) Crystal 4K Neo Seri...,Electronics,"HomeTheater,TV&Video",Televisions,SmartTelevisions,-,-,-,70900.00,0.32,47990.00,22910.00,4.30,7109.00,Resolution : Crystal 4K Ultra HD (3840 x 2160)...,"AHDIDVECFGA6OQRNUBPUO6366UGQ,AFSII6HTAHTHGXERU...","Binu,Sabjan,Ramkapil,User,Amazon Customer,gane...","R3RUBB6REUGTT,R281851EB9L5G6,R4ATJJVUY9JO6,R18...","Best(Branded) Budget TV,A high-quality 4k Smar...","Before finalizing the AUE60 55"", I visited Cro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,B0B3MQXNFB,FLiX (Beetel Flow USB to Micro USB PVC Data Sy...,Computers&Accessories,Accessories&Peripherals,Cables&Accessories,Cables,USBCables,-,-,199.00,0.71,57.89,141.11,4.00,9378.00,FLiX Flow Micro USB cable offers universal com...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...
616,B07KCMR8D6,Classmate Octane Neon- Blue Gel Pens(Pack of 5...,OfficeProducts,OfficePaperProducts,Paper,Stationery,"Pens,Pencils&WritingSupplies",Pens&Refills,GelInkRollerballPens,50.00,0.00,50.00,0.00,4.30,5792.00,5 vibrant Neon body color|Smooth and fast writ...,"AEVPRYZLGHNMEZA5BYGIX36LYZXA,AEZPOZQEEBFFXZ2EQ...","Gatij saini,Biswajit Kundu,Altaf Khan,Agam Sar...","RZAAQFY7BDSWC,R3604ZO2AA4PK5,R3C8K6Z6W9MDTQ,R3...","Nice ball pen,Good product,Average,Nice Pen,It...","Very nice ball pen,Thank you Amazon,Easy to ho..."
975,B08TDJ5BVF,E-COSMOS 5V 1.2W Portable Flexible USB LED Lig...,Computers&Accessories,Accessories&Peripherals,USBGadgets,Lamps,-,-,-,39.00,0.00,39.00,0.00,3.80,3344.00,The side the LED light falls on will depend on...,"AEEH5DFNKICJXQME6UXNS3P3OM3A,AGBSAL7DSIA2DOH4O...","Yugandhar Menda,Sonia,Amazon Customer,Placehol...","R3163MRJDEJMN7,RSQGCR6V7H766,R39PS8UO1CZS2D,R2...","Lighting,TINY & USEFUL.,Fair product,Worth for...","Recieved a wrong color.. But ok..,Simple and Q..."
997,B00URH5E34,Inventis 5V 1.2W Portable Flexible USB LED Lig...,Computers&Accessories,Accessories&Peripherals,USBGadgets,Lamps,-,-,-,39.00,0.00,39.00,0.00,3.60,13572.00,The side the LED light falls on will depend on...,"AGA4V2SLJ744MITK2FWWGPXOFB7A,AHDOHVS266NLKERWU...","Dhruv Sharma,Durairaj B,Ved Katyayan,Shailendr...","R1NAJ7CT76Z9SF,R17L9205IYOD,R2GAKH6NBQPCFV,R12...","it worked properly for almost one year,ok,USB ...","very good product, very bright, easy to use, i..."
645,B00MFPCY5C,GIZGA essentials Universal Silicone Keyboard P...,Computers&Accessories,Accessories&Peripherals,"Keyboards,Mice&InputDevices",Keyboard&MiceAccessories,DustCovers,-,-,299.00,0.87,39.00,260.00,3.50,15233.00,Universal Silicone Keyboard Protector Keyguard...,"AETHN2CGVNPVX5Y6SAWO6IO7QOEA,AFIZ6OD2C7QAISE7F...","Selva sibi,Apparao Yarra,priyanshu jha,Ashish ...","R3NB1CQXEVVQIT,R2I6VLGIXFKKU,R1G8SZJG03IY67,R2...","Good,Affordable and best,Check the size !,valu...","Value for money,Grt product,Please ensure the ..."

In [22]:
# Média de avaliações por categoria

cat_avaliation_mean = dfm.groupby('Category n0')['rating'].mean().reset_index(name='media_avaliaçãoes').sort_values(by='media_avaliaçãoes', ascending=False)
cat_avaliation_mean

             Category n0  media_avaliaçãoes
7         OfficeProducts               4.31
8             Toys&Games               4.30
5        HomeImprovement               4.25
1  Computers&Accessories               4.15
2            Electronics               4.08
4           Home&Kitchen               4.04
3    Health&PersonalCare               4.00
6     MusicalInstruments               3.90
0          Car&Motorbike               3.80

In [23]:
# Top 5 produtos com mais avaliazaçãoes

top_5_rating_count = dfm[['product_name','Category n0','rating_count']].sort_values(by='rating_count', ascending=False).head(5)
top_5_rating_count

,product_name,Category n0,rating_count
12,AmazonBasics Flexible Premium HDMI Cable (Blac...,Electronics,426973.00
65,"Amazon Basics High-Speed HDMI Cable, 6 Feet (2...",Electronics,426973.00
47,"Amazon Basics High-Speed HDMI Cable, 6 Feet - ...",Electronics,426973.00
684,AmazonBasics Flexible Premium HDMI Cable (Blac...,Electronics,426972.00
400,boAt Bassheads 100 in Ear Wired Earphones with...,Electronics,363713.00

In [24]:
# Considerações 4 - Qual categoria tem a melhor avaliação média (rating)? Quais os 5 produtos com mais avaliações (rating_count)?

print(f'A categoria com o maior desconto médio é a {med_desc_cat.iloc[0]["Category n0"]} com um desconto médio de {med_desc_cat.iloc[0]["media_desconto"]*100:.2f}%.')
print(f'Os cinco produtos com maior avaliação são:\n {top_5_rating_count[['product_name','rating_count']]}')

A categoria com o maior desconto médio é a HomeImprovement com um desconto médio de 57.50%.
Os cinco produtos com maior avaliação são:
                                           product_name  rating_count
12   AmazonBasics Flexible Premium HDMI Cable (Blac...     426973.00
65   Amazon Basics High-Speed HDMI Cable, 6 Feet (2...     426973.00
47   Amazon Basics High-Speed HDMI Cable, 6 Feet - ...     426973.00
684  AmazonBasics Flexible Premium HDMI Cable (Blac...     426972.00
400  boAt Bassheads 100 in Ear Wired Earphones with...     363713.00